-- 	item CardDeck
--	{
--	    DisplayCategory = Junk,
--		Weight	=	0.2,
--		Type	=	Normal,
--		DisplayName	=	Playing Cards,
--		Icon	=	CardDeck,
--		WorldStaticModel = CardDeck,
--	}

--	item Dice
--	{
--	    DisplayCategory = Junk,
--		Weight	=	0.2,
--		Type	=	Normal,
--		DisplayName	=	Dice,
--		Icon	=	Dice,
--		WorldStaticModel = Dice,
--	}

--    item GamePieceBlack
--    {
--        DisplayCategory = Junk,
--        Weight	=	0.1,
--        Type	=	Normal,
--        DisplayName	=	Black Game Pieces,
--        Icon	=	GamePieces_Black,
--        WorldStaticModel = GamePiecesBlack_Ground,
--    }
--
--    item GamePieceRed GamePieceBlack
--    {
--        DisplayCategory = Junk,
--        Weight	=	0.1,
--        Type	=	Normal,
--        DisplayName	=	Red Game Pieces,
--        Icon	=	GamePieces_Red,
--        WorldStaticModel = GamePiecesRed_Ground,
--    }
--
--    item GamePieceWhite GamePieceRed GamePieceBlack
--    {
--        DisplayCategory = Junk,
--        Weight	=	0.1,
--        Type	=	Normal,
--        DisplayName	=	White Game Pieces,
--        Icon	=	GamePieces_White,
--        WorldStaticModel = GamePiecesWhite_Ground,
--    }

--    item CheckerBoard GamePieceWhite GamePieceRed GamePieceBlack
--    {
--        DisplayCategory = Junk,
--        Weight	=	0.3,
--        Type	=	Normal,
--        DisplayName	=	Checkerboard,
--        Icon	=	CheckerBoard,
--        WorldStaticModel = CheckerBoard_Ground,
--    }

--    item BackgammonBoard CheckerBoard GamePieceWhite GamePieceRed GamePieceBlack
--    {
--        DisplayCategory = Junk,
--        Weight	=	0.3,
--        Type	=	Normal,
--        DisplayName	=	Backgammon Board,
--        Icon	=	BackgammonBoard,
--        WorldStaticModel = BackgammonBoard_Ground,
--    }

--    item PokerChips BackgammonBoard CheckerBoard GamePieceWhite GamePieceRed GamePieceBlack
--    {
--        DisplayCategory = Junk,
--        Weight	=	0.2,
--        Type	=	Normal,
--        DisplayName	=	Poker Chips,
--        Icon	=	PokerChips,
--        WorldStaticModel = PokerChips_Ground,
--    }

--     item ChessBlack PokerChips BackgammonBoard CheckerBoard GamePieceWhite GamePieceRed GamePieceBlack
--    {
--        DisplayCategory = Junk,
--        Weight	=	0.1,
--        Type	=	Normal,
--        DisplayName	=	Black Chess Pieces,
--        Icon	=	ChessBlack,
--        WorldStaticModel = BlackChessPieces,
--    }

--    item ChessWhite ChessBlack PokerChips BackgammonBoard CheckerBoard GamePieceWhite GamePieceRed GamePieceBlack
--    {
--        DisplayCategory = Junk,
--        Weight	=	0.1,
--        Type	=	Normal,
--        DisplayName	=	White Chess Pieces,
--        Icon	=	ChessWhite,
--        WorldStaticModel = WhiteChessPieces,
--    }